services:
  simplemqtt:
    build:
      context: ../../
      dockerfile: docker/SimpleMQTT/Dockerfile
    container_name: SimpleMQTT
    ports:
      - "1883:1883"  # MQTT TCP port
      - "8080:8080"  # WebSocket port
      - "8000:8000"  # HTTP port for test client
